# Generated by Django 2.2 on 2020-01-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to='pronounciations')),
            ],
        ),
    ]
